# Oracle profile configurations
spring.datasource.url=jdbc:oracle:thin:@//${DB_HOST:localhost}:${DB_PORT:1521}/${DB_SERVICE_NAME:ORCL}
spring.datasource.username=${DB_USER:system}
spring.datasource.password=${DB_PASSWORD:oracle}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
